# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.destroy_all
Weapon.destroy_all


 w1 = Weapon.create(  weaponsystem: "tank", name: "M4 Sherman", img_url: 'http://www.tanks-encyclopedia.com/ww2/US/Medium/M4/M4_Sherman_model42_belgium_45.png', role:  "Medium Tank", 
    country: "United States" ,
    side: "Allies",
    gun: "M2 L/32 or M3 L/40 75 mm (2.95 in) " ,
    ammo: "90 rounds",
    speed: "30 mph" ,
    armor: "Maximum 76 mm (3 in)",
    range: "120 mi",
      crew: 5,
      firepowergun: 3 ,
      firepowerammo: 5,
      speedscore: 5,
      health: 2,
      protection: 3 ,
      rangescore: 2,
      )
      
w2 = Weapon.create(

    weaponsystem: "tank",
      name: "T26E4 Super Pershing",
      img_url: 'http://www.tanks-encyclopedia.com/ww2/US/Heavy/M26_Pershing/T26A4_Super-Pershing.png',
      role: "Heavy/Medium Tank",
      country: "United States" ,
      side: "Allies",
      gun:"T15E1 or T15E2 90 mm tank gun (2.95 in)" ,
      ammo:"70 rounds",
      speed: "22 mph" ,
      armor: "100 mm (3.94 in)",
      range: "100 mi",
      crew: 5,
      firepowergun: 3 ,
      firepowerammo: 4,
      speedscore: 1,
      health: 3,
      protection: 4 ,
      rangescore: 1,
    )
   
    w3 = Weapon.create(
     weaponsystem: "tank",
      name: "3in GMC M10 “Wolverine”",
      img_url: 'http://www.tanks-encyclopedia.com/ww2/US/Tanks_Hunters/M10_Wolverine/M10_Wolverine_early.png',
      role: "Tank Killer",
      country: "United States" ,
      side: "Allies",
      gun:"3″ (76.2 mm) Gun M7" ,
      ammo:"54 rounds",
      speed: "32 mph " ,
      armor: "2.3 in (57.2 mm)",
      range: "186 mi",
      crew: 4,
      firepowergun: 3 ,
      firepowerammo: 3,
      speedscore: 5,
      health: 3,
      protection: 2 ,
      rangescore: 4,
    )
    w4 = Weapon.create(
        weaponsystem: "tank",
      name: "T-34/76”",
      img_url: 'http://www.tanks-encyclopedia.com/ww2/soviet/Medium_Tanks/T34-76/t34-76_sovietcamo.png',
      role: "Medium Tank",
      country: "Soviet Union" ,
      side: "Allies",
      gun:"F-34 76.2 mm (3 in) gun",
      ammo:"n/a",
      speed: "34 mph " ,
      armor: "up to 45 mm (1.77 in)",
      range: "186 mi",
      crew: 4,
      firepowergun: 3 ,
      firepowerammo: 3,
      speedscore: 5,
      health: 3,
      protection: 1 ,
      rangescore: 4,
    )
    w5 = Weapon.create(
      weaponsystem: "tank",
      name: "SU-100",
      img_url: 'http://www.tanks-encyclopedia.com/ww2/soviet/SPGs/SU-85-100/SU100-2.png',
      role: "Tank Destroyer",
      country: "Soviet Union" ,
      side: "Allies",
      gun:"100 mm (3.94 in) D-10S AT gun",
      ammo:"n/a",
      speed: "30 mph " ,
      armor: "75 mm (2.95 in)",
      range: "230 mi",
      crew: 4,
      firepowergun: 3 ,
      firepowerammo: 3,
      speedscore: 4,
      health: 3,
      protection: 3 ,
      rangescore: 5,
    )
    w6 = Weapon.create(
      weaponsystem: "tank",
      name: "IS-2",
      img_url: 'http://www.tanks-encyclopedia.com/ww2/soviet/Heavy_Tanks/IS-II/IS-II_29Guards_HTB_Poland45.png',
      role: "Heavy Tank",
      country: "Soviet Union" ,
      side: "Allies",
      gun:"122 mm (4.8 in) D-25T",
      ammo:"28 rounds",
      speed: "23 mph " ,
      armor: "120 mm (4.72 in)",
      range: "150 mi",
      crew: 4,
      firepowergun: 3 ,
      firepowerammo: 2,
      speedscore: 2,
      health: 3,
      protection: 5,
      rangescore: 3,
    )

    w7 = Weapon.create(
      weaponsystem: "tank",
      name: "Panzer V Panther",
      img_url: 'http://www.tanks-encyclopedia.com/ww2/nazi_germany/Medium_Tanks/Panzer-V_Panther/Panther_Ausf-D-1_Turm-IV.png',
      role: "Medium Tank",
      country: "Germany" ,
      side: "Axis",
      gun:"7.5 cm Kw.K.42 L/70",
      ammo:"79 rounds",
      speed: "34 mph " ,
      armor: " 80 mm",
      range: "124 mi",
      crew: 5,
      firepowergun: 3 ,
      firepowerammo: 4,
      speedscore: 5,
      health: 3,
      protection: 3 ,
      rangescore: 2,
    )

    w8 = Weapon.create(
        weaponsystem: "tank",
      name: "Jagdpanzer IV",
      img_url: 'http://www.tanks-encyclopedia.com/ww2/nazi_germany/Panzerjagers/Jagdpanzer-IV/Jagdpanzer-IV-L48_33PzAbt_15PZD_Italy1944.png',
      role: "Tank Hunter",
      country: "Germany" ,
      side: "Axis",
      gun:"7.5 cm (2.95 in) Pak 39 L/48 or Pak 42 L/70",
      ammo:"55 rounds",
      speed: "25 mph " ,
      armor: " 80 mm (3.15 in)",
      range: "130 mi",
      crew: 4,
      firepowergun: 3 ,
      firepowerammo: 3,
      speedscore: 2,
      health: 3,
      protection: 3 ,
      rangescore: 2,
    )
    w9 = Weapon.create(
        weaponsystem: "tank",
      name: "Jagdpanzer 38(t) Hetzer",
      img_url: 'http://www.tanks-encyclopedia.com/ww2/nazi_germany/Panzerjagers/Hetzer/Hetzer-Hun-winter44-45.png',
      role: "Tank Hunter",
      country: "Germany" ,
      side: "Axis",
      gun:"75 mm (2.95 in) PaK 39 L/48",
      ammo:"41 rounds",
      speed: "26 mph " ,
      armor: "  60 mm  (2.36 in)",
      range: "110 mi",
      crew: 4,
      firepowergun: 3 ,
      firepowerammo: 3,
      speedscore: 3,
      health: 3,
      protection: 2 ,
      rangescore: 2,
    ),

    w10 = Weapon.create(
        weaponsystem: "tank",
      name: "Panzer IV",
      img_url: 'http://www.tanks-encyclopedia.com/ww2/nazi_germany/Medium_Tanks/Panzer-IV/panzer_IV_AusfE.png',
      role: "Medium Tank",
      country: "Germany" ,
      side: "Axis",
      gun:"7.5 cm Kw.K L/24 gun",
      ammo:"87 rounds",
      speed: "20 mph " ,
      armor: "  30 mm ",
      range: "130 mi",
      crew: 5,
      firepowergun: 3 ,
      firepowerammo: 5,
      speedscore: 1,
      health: 3,
      protection: 1 ,
      rangescore: 2,
    ),

    w11 = Weapon.create(
      weaponsystem: "tank",
      name: "Panzer VI Tiger",
      img_url: 'http://www.tanks-encyclopedia.com/ww2/nazi_germany/Heavy_Tanks/Panzer-VI_Tiger/VK4501_PzKpfwVI_Tiger-P_SdKfz-181.png',
      role: "Heavy Tank",
      country: "Germany" ,
      side: "Axis",
      gun:"88 mm (3.4 in) KwK 36 L/56",
      ammo:" 92-120 rounds",
      speed: "28 mph " ,
      armor: "  100 mm ",
      range: "77.67 miles",
      crew: 5,
      firepowergun: 3 ,
      firepowerammo: 5,
      speedscore: 3,
      health: 3,
      protection: 4 ,
      rangescore: 3,
    )

    w12 = Weapon.create(
        weaponsystem: "plane",
      name: "P-51 Mustang",
      img_url: 'http://www.aircraftaces.com/images/p51-mustang.jpg',
      role: "Fighter Plane",
      country: "United States" ,
      side: "Allies",
      gun: "6 X .50 caliber (12.7mm) AN/M2 Browning Machine Guns "  ,
      ammo: "Two 227 kgs (500 lbs) bombs",
      armor:"12,770 meters (41,900 feet)",
      speed: "716 kmh (445 mph)",
      range:"525 km (326 miles)",
      crew: 1,
        firepowergun: 3 ,
        firepowerammo: 3,
        speedscore: 3,
        health: 3,
        protection: 2 ,
        rangescore: 2,
       )  

    w13 = Weapon.create(
        weaponsystem: "plane",
      name: "Vought F4U Corsair",
      img_url: 'http://www.aircraftaces.com/images/f4u-corsair.jpg',
      role: "Fighter Plane",
      country: "United States" ,
      side: "Allies",
      gun: "Six 12.77 mm (0.50 cal) Browning M2 machine-guns with 400 rounds (outboard) and 375 rounds (inboard) per gun "  ,
      ammo: "1800 kg (4,000 lbs) of bombs or rockets",
      armor:"11,247 meters (37,000 feet)",
        speed: "671 kmh (417 mph)",
        range:"1650 km (1,010 miles)",
        crew: "",
        firepowergun: 3 ,
        firepowerammo: 3,
        speedscore: 3,
        health: 3,
        protection: 2 ,
        rangescore: 2,
        )  

      w14 = Weapon.create(
        weaponsystem: "plane",
      name: "Focke Wulf Fw 190A",
      img_url: 'http://www.aircraftaces.com/images/fw-190.jpg',
      role: "Bomber Plane",
      country: "German" ,
      side: "Axis",
      gun: "Two 7.92 mm (0.31 in) MG 17 machine guns, Four 20 mm (0.79 in) MG 151/20 cannon"  ,
      ammo: "One 500 kg (1,100 lbs), Two 250 kg (550 lbs) bombs",
      armor:"11,400 meters (37,400 feet)",
        speed: "654 kmh (406 mph)",
        range:"800 km (497 miles)",
        crew: 1,
        firepowergun: 3 ,
        firepowerammo: 3,
        speedscore: 3,
        health: 3,
        protection: 2 ,
        rangescore: 2,
       )    
      
       w15 = Weapon.create(
        weaponsystem: "plane",
      name: "Messerschmitt Me 262",
      img_url: 'http://www.aircraftaces.com/images/me-262.jpg',
      role: "Fighter Plane",
      country: "German" ,
      side: "Axis",
      gun: "Four Rheinmetall Borsig Mk 108A-3 30mm cannons in the nose",
      ammo: "Two 226 kg (500 lbs) bombs or one 452 kg (1,000 lbs) bomb",
      armor:"11,450 meters (37,500 feet)",
      speed: "870 kmh (540 mph)",
      range:"1050 km (650 miles)",
      crew: "",
      firepowergun: 3 ,
      firepowerammo: 3,
      speedscore: 3,
      health: 3,
      protection: 2 ,
      rangescore: 2,
       )

       w16 = Weapon.create(
        weaponsystem: "plane",
        name: "Messerschmitt Bf 109",
        img_url: 'http://www.aircraftaces.com/images/bf-109.jpg',
        role: "Fighter Plane",
        country: "German" ,
        side: "Axis",
        gun: "One engine mounted 20 mm (0.79 in) MG FF cannon, Four 7.9 mm (0.31 in) MG 17 machine-guns",
        ammo: "None",
        armor:"10,500 meters (34,400 feet)",
        speed: "560 kmh (347 mph)",
        range:"660 km (410 miles)",
        crew: "",
        firepowergun: 3 ,
        firepowerammo: 3,
        speedscore: 3,
        health: 3,
        protection: 2 ,
        rangescore: 2,
         ) 

      w17 = Weapon.create(
        weaponsystem: "plane",
        name: "Supermarine Spitfire",
        img_url: 'http://www.aircraftaces.com/images/spitfire.jpg',
        role: "Fighter Plane",
        country: "United Kingdom" ,
        side: "Allies",
        gun: "Eight 7.7 mm (0.303 cal) Browning machine-guns with 350 rounds per gun",
        ammo: "None",
        armor:"11,125 meters (37,000 feet)",
        speed: "594 kmh (374 mph)",
        range:"1827 km (1,135 miles)",
        crew: "",
        firepowergun: 3 ,
        firepowerammo: 3,
        speedscore: 3,
        health: 3,
        protection: 2 ,
        rangescore: 2,
         )

      w18 = Weapon.create(
        weaponsystem: "plane",
        name: "Mitsubishi A6M Zero",
        img_url: 'http://www.aircraftaces.com/images/mitsubishi-a6m-zero.jpg',
        role: "Fighter Plane",
        country: "Imperial Japan" ,
        side: "Axis",
        gun: "Two 7.7 mm (0.303 cal) machine-guns with 600 rounds above the engine , Two 20 mm (0.79 in) Type 99 cannon with 100 rounds each in the wings",
        ammo: "Tw0 60 kg (130 lbs) bombs under wings (suicide mission, one 250 kg/550 lb bomb)",
        armor:"11,740 meters (38,500 feet)",
        speed: "565 kmh (350 mph)",
        range:"1,800 km (1,200 miles)",
        crew: "",
        firepowergun: 3 ,
        firepowerammo: 3,
        speedscore: 3,
        health: 3,
        protection: 2 ,
        rangescore: 2,
         ),

        w19 = Weapon.create(
        weaponsystem: "plane",
        name: "Junkers Ju 87 Stuka",
        img_url: 'http://www.aircraftaces.com/images/junkers-87-stuka.jpg',
        role: "Two-seat dive bomber and attack aircraft",
        country: "German" ,
        side: "Axis",
        gun: "One 7.92 mm (0.31 in) machine gun in wings, Two 7.92 mm MG 81Z guns in rear cockpit",
        ammo: "A bomb of 1,800 kg (3,960 lbs) beneath fuselage",
        armor:"7,290 meters (23,910 feet)",
        speed: "410 kmh (254 mph)",
        range:"1,535 km (950 miles)",
        crew: "",
        firepowergun: 3 ,
        firepowerammo: 3,
        speedscore: 3,
        health: 3,
        protection: 2 ,
        rangescore: 2,
         )

         w20 = Weapon.create(
            weaponsystem: "plane",
        name: "Ilyushin 2/10 Sturmovik",
        img_url: 'http://www.aircraftaces.com/images/il-2-sturmovik.jpg',
        role: "One or two-seat armoured close-support aircraft",
        country: "Soviet Union" ,
        side: "Allies",
        gun: "Two 20 mm (0.79 in) or two 37 mm (1.47 in) cannon in wings ",
        ammo: "600 kg (1,320 lbs) of bombs",
        armor:"9,700 meters (31,825 feet)",
        speed: "430 kmh (267 mph)",
        range:"600 km (375 miles)",
        crew: "",
        firepowergun: 3 ,
        firepowerammo: 3,
        speedscore: 3,
        health: 3,
        protection: 2 ,
        rangescore: 2,
         )
         
         
         w21 = Weapon.create(
            weaponsystem: "plane",
        name: "Curtiss P-40 Warhawk",
        img_url: 'http://www.aircraftaces.com/images/curtiss-warhawk.jpg',
        role: "Single seat interceptor fighter bomber",
        country: "United States" ,
        side: "Allies",
        gun: "Six 12.7mm (0.50 cal) machine guns in wing ",
        ammo: "provision for 227 kg (500 lbs) bomb",
        armor:"11,630 meters (38,160 feet)",
        speed: "609 kmh (378 mph)",
        range:"386 km (240 miles)",
        crew: "",
        firepowergun: 3 ,
        firepowerammo: 3,
        speedscore: 3,
        health: 3,
        protection: 2 ,
        rangescore: 2,
  )

  
      userOne = User.create(username: "UserOne", firstname: "J1", lastname:'H1', password: "pass1")
      userTwo = User.create(username: "UserTwo", firstname: "J2", lastname:'H2', password: "pass2")
      userThree = User.create(username: "UserThree", firstname: "J3", lastname:'H3', password: "pass3")
      
      

